### ISSUE TITLE
Field doesn't not work inside a repeater

### ISSUE THREAD

**Issue by graham73may** [CondeNastDigital/cnBolt-Extensions-RelationList#8]
Using a relationlist field in a repeater caused my backend to render in an unusable state. (screenshot attached)

Bolt 3.2.2

![image](https://cloud.githubusercontent.com/assets/6642498/20530288/d9d51d20-b0ca-11e6-8812-6029d7d23bf0.png)

```
  ft_content_cards:
            group: "Featured content"
            label: "Cards"
            type: repeater
            fields:
                item:
                    label: "Featured item"
                    type: relationlist
                    allowed-types: [ pages, news, resources, research, projects, events, people, jobs, charts, media ]
                    min: 1
                    max: 1
```
